name: Release container

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build container
      run: just build-container

  publish:
    runs-on: self-hosted
    name: Publish container
    needs: build
    steps:
      - name: Login to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Publish image
        run: |
          podman push ghcr.io/virto-network/virto-proxy:$(just version)
          podman push ghcr.io/virto-network/virto-proxy:latest
